spring.application.name=etecfer

    # Configuração do Banco de Dados
    spring.datasource.url=jdbc:postgresql://localhost:5432/etecfer_db
    spring.datasource.username=postgres
    spring.datasource.password=postdba

     #Atulizar as tabelas do Banco de dados automaticamente
     spring.jpa.hibernate.ddl-auto=update

     #Não formatar os comandos SQL no console 
     spring.jpa.properties.hipernate.format.sql=false

     #Mostrar os comandos SQL no console
     spring.jpa.show-sql=true

     #configurar a porta do servidor
     server.port=8080


